"""empty message

Revision ID: 429291c2c7f5
Revises: 348541b6eb05
Create Date: 2023-03-13 17:18:12.098538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429291c2c7f5'
down_revision = '348541b6eb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=256), nullable=False, server_default='lorem ipsum',))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
